import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
  actionList: {
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    padding: 6,
    borderWidth: 1,
    borderColor: "#A3A29D",
    backgroundColor: "#FBFBFB",
  },
  selectedList: {
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    padding: 6,
    borderWidth: 1,
    borderColor: "#A3A29D",
    backgroundColor: "#EFEFEF",
    flex: 1,
    borderRightWidth: 0,
  },
  selectDelete: {
    justifyContent: "center",
    alignItems: "center",
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#b91c1c",
    backgroundColor: "#fef2f2",
    flex: 1,
  },
  back: {
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: "#FBFBFB",
    borderColor: "#E3E3E3",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 16,
  },
  scrollContainer: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: "#FBFBFB",
    borderColor: "#E3E3E3",
  },
  head: {
    borderBottomWidth: 1,
    backgroundColor: "#FBFBFB",
    borderColor: "#E3E3E3",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  save: {
    borderRadius: 12,
    backgroundColor: "#37352F",
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 16,
  },
});

export default styles;
