import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  cardTop: {
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    borderWidth: 1,
    flex: 1,
    width: 70,
    borderBottomWidth: 0,
    borderColor: "#A3A29D",
    backgroundColor: "#FBFBFB",
  },
  iconContainer: {
    backgroundColor: "#FBFBFB",
    borderRadius: 12,
    padding: 4,
  },
  cardRemove: {
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#b91c1c",
    width: 70,
    padding: 1,
  },
  removeText: { marginBottom: 2, color: "#b91c1c" },
  boardContainer: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: "#FBFBFB",
    borderWidth: 1,
    borderColor: "#E3E3E3",
    position: "relative",
  },
  stripContainer: {
    marginTop: 8,
    flexDirection: "row",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E3E3E3",
    backgroundColor: "#FBFBFB",
  },
  execute: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: "#37352F",
    paddingHorizontal: 16,
    paddingVertical: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  plusContainer: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FBFBFB",
    borderColor: "#E3E3E3",
    borderWidth: 1,
    width: 70,
  },
  plusV: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
    borderWidth: 1.5,
    borderColor: "#A3A29D",
    borderRadius: 99,
    padding: 6,
    backgroundColor: "#EFEFEF",
  },
  plusv: {
    width: 1.5,
    height: "100%",
    borderRadius: 99,
    flex: 1,
    position: "absolute",
    backgroundColor: "#A3A29D",
  },
  plusx: {
    height: 1.5,
    flex: 1,
    width: "100%",
    borderRadius: 99,
    position: "absolute",
    backgroundColor: "#A3A29D",
  },
  greenDot: {
    width: 8,
    height: 8,
    position: "absolute",
    borderRadius: 12,
    backgroundColor: "#00D200",
    zIndex: 9,
    margin: 6,
  },
  midText: {
    flex: 1,
    padding: 12,
    justifyContent: "center",
    alignItems: "center",
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: "#E3E3E3",
  },
});

export default styles;
